/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rdict.h"
#include "dict.c"

int *
initw_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
        printf ("Init dict \n");
	result = initw();
	return &result;
}

int *
insertw_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
        printf ("Insert dict \n");
	printf("%s inserted.\n",*argp);
	result = insertw(*argp);
	return &result;
}

int *
deletew_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = deletew(*argp);
	return &result;
}

int *
lookupw_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = lookupw(*argp);
	return &result;
}
